### ISSUE TITLE
3. GitHub Actions - Examples

### ISSUE THREAD

**Issue by taoliujun** [taoliujun/taoliujun.github.io#7]
官方文档：https://docs.github.com/en/actions/examples/using-scripts-to-test-your-code-on-a-runner

官方描述了3个例子，用来检测文件中的broken，我读书少，就依葫芦画瓢写一个eslint检测增量文件的功能，完成以下功能：

* pull_request触发workflow。
* 使用eslint检查pull request的增量文件。
* 如果检查失败，回复失败的文件和内容。
* 如果检查成功，回复"+LGTM by eslint"。

例子中一些术语或属性是第一次出现，先不要管，简单查阅下文档先完成功能，后续文章再研究它们。

## 准备工作

* `package.json`中存在`eslint`依赖。
* 存在配置文件 `.eslintrc.js`。

## 基础的配置

写一个简单的Job让它先跑起来：

```yaml
name: pull_request
on: pull_request
jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - run: echo "i am eslint"
```

##增量检查

列出pull request的修改、新增的js、ts文件，先不用管eslint，只打印出这些文件。

TODO

**等我学习了后续的知识，再来补充这个例子！！！** 

**等我学习了后续的知识，再来补充这个例子！！！**

**等我学习了后续的知识，再来补充这个例子！！！**
